import { Minus, Plus, ShoppingBag, Trash2, X } from "lucide-react";
import type { Product } from "../../../../drizzle/schema";

type CartLine = { product: Product; quantity: number; optionKey: string; unitPrice: number };
const labels: Record<string, string> = { "100g": "100غ", "250g": "250غ", "500g": "500غ", "1kg": "1 كيلو" };

export function CartDrawer({ open, items, currency, onClose, onChangeQuantity, onRemove, onCheckout }: { open: boolean; items: CartLine[]; currency: string; onClose: () => void; onChangeQuantity: (productId: number, optionKey: string, quantity: number) => void; onRemove: (productId: number, optionKey: string) => void; onCheckout: () => void }) {
  if (!open) return null;
  const subtotal = items.reduce((sum, item) => sum + item.unitPrice * item.quantity, 0);
  return <div className="fixed inset-0 z-[80]"><button className="absolute inset-0 bg-black/65 backdrop-blur-sm" onClick={onClose} aria-label="إغلاق السلة" /><aside className="drawer-panel cart-drawer absolute inset-y-0 right-0 flex w-full max-w-md flex-col border-l border-white/10 bg-[#141210] shadow-2xl"><div className="flex items-center justify-between border-b border-white/10 px-5 py-5"><div><p className="text-[10px] tracking-[0.25em] text-[#d6b56b]">YOUR EDIT</p><h2 className="font-serif text-2xl">السلة</h2></div><button onClick={onClose} className="icon-button"><X size={20} /></button></div><div className="flex-1 overflow-y-auto p-5">{items.length === 0 ? <div className="flex h-full flex-col items-center justify-center text-center"><div className="mb-4 rounded-full border border-[#d6b56b]/20 bg-[#d6b56b]/10 p-5 text-[#d6b56b]"><ShoppingBag size={28} /></div><h3 className="mb-2 font-serif text-xl">سلتك بانتظار لمستك</h3><p className="max-w-xs text-sm leading-7 text-[#989188]">أضف قطعة أو أكثر من مجموعتنا لبدء طقسك الخاص.</p></div> : <div className="space-y-4">{items.map(({ product, quantity, optionKey, unitPrice }) => <div key={`${product.id}-${optionKey}`} className="flex gap-3 rounded-2xl border border-white/10 bg-white/[0.03] p-3"><img src={product.imageUrl} alt={product.name} className="h-20 w-20 rounded-xl object-cover" /><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><div><h3 className="truncate font-serif text-base">{product.name}</h3><p className="mt-1 text-xs text-[#8f887e]">{labels[optionKey] || optionKey} · {unitPrice.toFixed(2)} {currency}</p></div><button onClick={() => onRemove(product.id, optionKey)} className="text-[#8c8173] transition-colors hover:text-rose-300"><Trash2 size={16} /></button></div><div className="mt-3 flex items-center justify-between"><div className="flex items-center gap-2 rounded-full border border-white/10 px-2 py-1"><button onClick={() => onChangeQuantity(product.id, optionKey, quantity - 1)} className="text-[#d6b56b]"><Minus size={14} /></button><span className="min-w-5 text-center text-xs">{quantity}</span><button onClick={() => onChangeQuantity(product.id, optionKey, quantity + 1)} className="text-[#d6b56b]"><Plus size={14} /></button></div><span className="font-serif text-sm text-[#e6d7b9]">{(unitPrice * quantity).toFixed(2)} {currency}</span></div></div></div>)}</div>}</div>{items.length > 0 && <div className="cart-drawer-footer border-t border-white/10 p-5"><div className="mb-4 flex items-center justify-between text-sm"><span className="text-[#9a9288]">الإجمالي الفرعي</span><span className="font-serif text-xl text-[#d6b56b]">{subtotal.toFixed(2)} {currency}</span></div><button onClick={onCheckout} className="gold-button w-full">إتمام الطلب</button><p className="mt-3 text-center text-[11px] leading-5 text-[#80776d]">الدفع عند الاستلام متاح · الشحن يحسب في الخطوة التالية</p></div>}</aside></div>;
}
